// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/growit-almanac/Almanac.tsx": () => import("../components/mockups/growit-almanac/Almanac.tsx"),
  "./components/mockups/growit-greenhouse/Greenhouse.tsx": () => import("../components/mockups/growit-greenhouse/Greenhouse.tsx")
};
